### ISSUE TITLE
Automatic screenshots of webpages

### ISSUE THREAD

**Issue by xt1** [SuperOfficeDocs/superoffice-docs#628]
As we add more languages, we need screenshots of parts of the application in the appropriate languages.
e.g. norwegian docs should have norwegian screenshots

Automate the taking of screenshots. Describe the element of the screen to take a screenshot of and let a program take the screenshot in 7 different languages.

I've written a program to help do this: webshooter.exe uses Playwright to drive Chromium around the application and take screenshots. 
Screenshots are defined in a yaml file:

```yml
- Output: media/login.png
  Url: https://sod.superoffice.com/
  Element: ".containerInner"
```

You can string multiple screenshots in the same file, you can provide secrets via properties on the command line or via environment variables.

**Comment by xt1** [comment]
# Webshooter command-line

 ` -p, --prop`            Define property that can be `{{referenced}}` in shot files

 ` -v, --verbose`         Set output to verbose messages. Use -vv for more verbosity.

 `-s, --show`            Show browser window.

  `-u, --url`             Base URL to use for requests.

  `-o, --outputDir`       Output directory for images.

  `-H, --shotFileHelp`    Describe shot file format.

  `values`          Required. YML file or folders to search for .shot files

`webshooter.exe -v -s docs -p Password=foobar`
`webshooter.exe Shots\Google.yml Shots\Bing.yml -o out`

# Shot files

Shot files are YAML files that contain description of web-page elements and instruction 
on how to take the screenshot.
Properties or environment variables are substituted for {{name}}s in strings, so
that you don't need to check in secrets.

* `Output`: string - path to write PNG screenshot to, relative to the output directory.
        Blank = don't take screenshot.
* `Url`: string - URL to load. Optional. Can be relative to BaseUrl (if specified). 
        Blank = continue with current browser state.
* `WindowSize`: string '900x600' - width x height in pixels. Optional. Resizes window.
* `Element`: string - CSS or XPath locator for element to take screenshot of. 
        Blank = whole screen.
* `Before`: array of Steps to do before taking the shot. Optional.
* `After`: array of Steps to do after taking the shot. Optional.

**Steps**: one of the following.

* `Click`: string - CSS or XPath locator of element to click. Waits for element 
        to be visible.
* `WaitForVisible`: string - CSS or XPath locator of element to wait for.
* `WaitForHidden`: string - CSS or XPath locator of element to wait for.
* `WaitForUrl`: string - URL glob expression. Waits for URL to match expression.
* `Type`: TypeStep - enters text into a location.
  - `Element`: string - CSS or XPath locator of element to type into.
  - `Text`: string - text to enter into the element.

## Example:
```yml
    - Output: login.png
      WindowSize: 800x800
      Url: http://sod.superoffice.com/
      Element: ".containerInner"
      Before:
        - Type: 
            Element: "#Username"
            Text: "username@example.com"
        - Click: "#nextButton"
        - Type: 
            Element: "#Password"
            Text: "{{LoginPassword}}" # substitute with prop or env.var
      After:
        - Click: "#loginButton"
```
